### ISSUE TITLE
Failing with Babel 6.5 CLI

### ISSUE THREAD

**Issue by nkbt** [istarkov/babel-plugin-webpack-loaders#15]
As soon as babel 6.5 was released, tests I've been running with no problem started to fail hard.

Example of the failed build: https://circleci.com/gh/nkbt/react-component-template/321

```sh
$(npm bin)/babel-node test | $(npm bin)/tap-xunit > ${CIRCLE_TEST_REPORTS}/test.xml && test ${PIPESTATUS[0]} -eq 0
/home/ubuntu/react-component-template/node_modules/babel-core/lib/transformation/file/index.js:585
      throw err;
      ^

TypeError: /home/ubuntu/react-component-template/src/example/App.js: Cannot read property 'start' of undefined
    at /home/ubuntu/react-component-template/node_modules/babel-generator/lib/whitespace.js:29:19
    at Whitespace._findToken (/home/ubuntu/react-component-template/node_modules/babel-generator/lib/whitespace.js:99:30)
    at Whitespace._findToken (/home/ubuntu/react-component-template/node_modules/babel-generator/lib/whitespace.js:101:19)
    at Whitespace._findToken (/home/ubuntu/react-component-template/node_modules/babel-generator/lib/whitespace.js:101:19)
    at Whitespace._findToken (/home/ubuntu/react-component-template/node_modules/babel-generator/lib/whitespace.js:101:19)
    at Whitespace._findToken (/home/ubuntu/react-component-template/node_modules/babel-generator/lib/whitespace.js:101:19)
    at Whitespace._findToken (/home/ubuntu/react-component-template/node_modules/babel-generator/lib/whitespace.js:101:19)
    at Whitespace.getNewlinesBefore (/home/ubuntu/react-component-template/node_modules/babel-generator/lib/whitespace.js:28:22)
    at CodeGenerator._printNewline (/home/ubuntu/react-component-template/node_modules/babel-generator/lib/printer.js:271:33)
    at CodeGenerator.print (/home/ubuntu/react-component-template/node_modules/babel-generator/lib/printer.js:85:10)
    at CodeGenerator.printJoin (/home/ubuntu/react-component-template/node_modules/babel-generator/lib/printer.js:193:12)
    at CodeGenerator.printList (/home/ubuntu/react-component-template/node_modules/babel-generator/lib/printer.js:258:17)
    at CodeGenerator.ObjectExpression (/home/ubuntu/react-component-template/node_modules/babel-generator/lib/generators/types.js:48:10)
    at CodeGenerator._print (/home/ubuntu/react-component-template/node_modules/babel-generator/lib/printer.js:155:17)
    at CodeGenerator.print (/home/ubuntu/react-component-template/node_modules/babel-generator/lib/printer.js:91:10)

at CodeGenerator.VariableDeclarator (/home/ubuntu/react-component-template/node_modules/babel-generator/lib/generators/statements.js:306:10) $(npm bin)/babel-node test | $(npm bin)/tap-xunit > ${CIRCLE_TEST_REPORTS}/test.xml && test ${PIPESTATUS[0]} -eq 0 returned exit code 1
```

When I commented out inclusion of `App.js` which itself includes `App.css` - everything is back to normal.

```js
import test from 'tape';
//import App from '../../src/example/App';


test('App', t => {
//  t.ok(App instanceof Function, 'should be function');
  t.end();
});
```

`App.js` -> https://github.com/nkbt/react-component-template/blob/master/src/example/App.js

`.babelrc` -> https://github.com/nkbt/react-component-template/blob/master/.babelrc

Feel free to close the ticket if it is too specific case. I just wanted to check if I am alone with it.

Will debug a bit later

**Comment by istarkov** [comment]
The same on local test, will look today

**Comment by istarkov** [comment]
Fixed, thank you.

**Comment by MoOx** [comment]
Facing this bug since yesterday. Thanks for fixing it :+1:

**Comment by thangngoc89** [comment]
Thanks for fixing it :+1:

**Comment by MoOx** [comment]
Hum... @istarkov I am still having an issue:

https://travis-ci.org/MoOx/statinamic/jobs/107962783

Here is the code https://github.com/MoOx/statinamic/blob/babel-node-loaders/src/md-collection-loader/__tests__/feed.js

If I move the feed() call and the string out of the t() call (as const) I don't have the issue anymore.

**Comment by istarkov** [comment]
@MoOx So many code ;-) I even can't get where this plugin is used. Is any possibility to create failing test example here https://github.com/istarkov/babel-plugin-webpack-loaders/tree/master/test

**Comment by nkbt** [comment]
All fixed for me, thanks a lot!

**Comment by MoOx** [comment]
@istarkov you can close. I am getting the same issue (same error message) but not your fault https://github.com/sindresorhus/ava/issues/538 (still related to the babel update).

**Comment by istarkov** [comment]
la la la la la la la la :-)
